UPDATE public.scraper_info
set    last_repo_id = 461309499;

INSERT INTO public.users (id,user_id,login,name,email,html_url,avatar_url,bio,company,created_at,blog,followers,following,gravatar_id,hireable,location,node_id,public_gists,public_repos,site_admin,twitter_username,type,updated_at,url) VALUES
	 (1,16350390,'andrealoisio',NULL,NULL,'https://github.com/andrealoisio','https://avatars.githubusercontent.com/u/16350390?v=4',NULL,NULL,NULL,NULL,NULL,NULL,'',NULL,NULL,'MDQ6VXNlcjE2MzUwMzkw',NULL,NULL,false,NULL,'User',NULL,'https://api.github.com/users/andrealoisio'),
	 (2,82260676,'kerim47',NULL,NULL,'https://github.com/kerim47','https://avatars.githubusercontent.com/u/82260676?v=4',NULL,NULL,NULL,NULL,NULL,NULL,'',NULL,NULL,'MDQ6VXNlcjgyMjYwNjc2',NULL,NULL,false,NULL,'User',NULL,'https://api.github.com/users/kerim47'),
	 (3,9325425,'tsahaca',NULL,NULL,'https://github.com/tsahaca','https://avatars.githubusercontent.com/u/9325425?v=4',NULL,NULL,NULL,NULL,NULL,NULL,'',NULL,NULL,'MDQ6VXNlcjkzMjU0MjU=',NULL,NULL,false,NULL,'User',NULL,'https://api.github.com/users/tsahaca'),
	 (4,98195982,'FullStackJustin',NULL,NULL,'https://github.com/FullStackJustin','https://avatars.githubusercontent.com/u/98195982?v=4',NULL,NULL,NULL,NULL,NULL,NULL,'',NULL,NULL,'U_kgDOBdpaDg',NULL,NULL,false,NULL,'User',NULL,'https://api.github.com/users/FullStackJustin'),
	 (5,70615264,'amaruyum',NULL,NULL,'https://github.com/amaruyum','https://avatars.githubusercontent.com/u/70615264?v=4',NULL,NULL,NULL,NULL,NULL,NULL,'',NULL,NULL,'MDQ6VXNlcjcwNjE1MjY0',NULL,NULL,false,NULL,'User',NULL,'https://api.github.com/users/amaruyum'),
	 (6,83042710,'faves4less',NULL,NULL,'https://github.com/faves4less','https://avatars.githubusercontent.com/u/83042710?v=4',NULL,NULL,NULL,NULL,NULL,NULL,'',NULL,NULL,'MDQ6VXNlcjgzMDQyNzEw',NULL,NULL,false,NULL,'User',NULL,'https://api.github.com/users/faves4less'),
	 (7,60597290,'rashidwassan',NULL,NULL,'https://github.com/rashidwassan','https://avatars.githubusercontent.com/u/60597290?v=4',NULL,NULL,NULL,NULL,NULL,NULL,'',NULL,NULL,'MDQ6VXNlcjYwNTk3Mjkw',NULL,NULL,false,NULL,'User',NULL,'https://api.github.com/users/rashidwassan'),
	 (8,93694596,'chiba1999525',NULL,NULL,'https://github.com/chiba1999525','https://avatars.githubusercontent.com/u/93694596?v=4',NULL,NULL,NULL,NULL,NULL,NULL,'',NULL,NULL,'U_kgDOBZWqhA',NULL,NULL,false,NULL,'User',NULL,'https://api.github.com/users/chiba1999525'),
	 (9,12820826,'DrRobertMurphy',NULL,NULL,'https://github.com/DrRobertMurphy','https://avatars.githubusercontent.com/u/12820826?v=4',NULL,NULL,NULL,NULL,NULL,NULL,'',NULL,NULL,'MDQ6VXNlcjEyODIwODI2',NULL,NULL,false,NULL,'User',NULL,'https://api.github.com/users/DrRobertMurphy'),
	 (10,100047446,'Fab583',NULL,NULL,'https://github.com/Fab583','https://avatars.githubusercontent.com/u/100047446?v=4',NULL,NULL,NULL,NULL,NULL,NULL,'',NULL,NULL,'U_kgDOBfaaVg',NULL,NULL,false,NULL,'User',NULL,'https://api.github.com/users/Fab583');
INSERT INTO public.users (id,user_id,login,name,email,html_url,avatar_url,bio,company,created_at,blog,followers,following,gravatar_id,hireable,location,node_id,public_gists,public_repos,site_admin,twitter_username,type,updated_at,url) VALUES
	 (11,73558557,'awelawi',NULL,NULL,'https://github.com/awelawi','https://avatars.githubusercontent.com/u/73558557?v=4',NULL,NULL,NULL,NULL,NULL,NULL,'',NULL,NULL,'MDQ6VXNlcjczNTU4NTU3',NULL,NULL,false,NULL,'User',NULL,'https://api.github.com/users/awelawi'),
	 (12,89318337,'Fatimaines',NULL,NULL,'https://github.com/Fatimaines','https://avatars.githubusercontent.com/u/89318337?v=4',NULL,NULL,NULL,NULL,NULL,NULL,'',NULL,NULL,'MDQ6VXNlcjg5MzE4MzM3',NULL,NULL,false,NULL,'User',NULL,'https://api.github.com/users/Fatimaines'),
	 (13,100036577,'Leocl745',NULL,NULL,'https://github.com/Leocl745','https://avatars.githubusercontent.com/u/100036577?v=4',NULL,NULL,NULL,NULL,NULL,NULL,'',NULL,NULL,'U_kgDOBfZv4Q',NULL,NULL,false,NULL,'User',NULL,'https://api.github.com/users/Leocl745'),
	 (14,73328740,'riteshmishra253',NULL,NULL,'https://github.com/riteshmishra253','https://avatars.githubusercontent.com/u/73328740?v=4',NULL,NULL,NULL,NULL,NULL,NULL,'',NULL,NULL,'MDQ6VXNlcjczMzI4NzQw',NULL,NULL,false,NULL,'User',NULL,'https://api.github.com/users/riteshmishra253'),
	 (15,92962705,'rafacruz78gt',NULL,NULL,'https://github.com/rafacruz78gt','https://avatars.githubusercontent.com/u/92962705?v=4',NULL,NULL,NULL,NULL,NULL,NULL,'',NULL,NULL,'U_kgDOBYp_kQ',NULL,NULL,false,NULL,'User',NULL,'https://api.github.com/users/rafacruz78gt'),
	 (16,100047450,'ForeroPaola',NULL,NULL,'https://github.com/ForeroPaola','https://avatars.githubusercontent.com/u/100047450?v=4',NULL,NULL,NULL,NULL,NULL,NULL,'',NULL,NULL,'U_kgDOBfaaWg',NULL,NULL,false,NULL,'User',NULL,'https://api.github.com/users/ForeroPaola'),
	 (17,95763600,'Zoro125',NULL,NULL,'https://github.com/Zoro125','https://avatars.githubusercontent.com/u/95763600?v=4',NULL,NULL,NULL,NULL,NULL,NULL,'',NULL,NULL,'U_kgDOBbU8kA',NULL,NULL,false,NULL,'User',NULL,'https://api.github.com/users/Zoro125'),
	 (18,1591200,'magenx',NULL,NULL,'https://github.com/magenx','https://avatars.githubusercontent.com/u/1591200?v=4',NULL,NULL,NULL,NULL,NULL,NULL,'',NULL,NULL,'MDQ6VXNlcjE1OTEyMDA=',NULL,NULL,false,NULL,'User',NULL,'https://api.github.com/users/magenx'),
	 (19,61332171,'dzendruid',NULL,NULL,'https://github.com/dzendruid','https://avatars.githubusercontent.com/u/61332171?v=4',NULL,NULL,NULL,NULL,NULL,NULL,'',NULL,NULL,'MDQ6VXNlcjYxMzMyMTcx',NULL,NULL,false,NULL,'User',NULL,'https://api.github.com/users/dzendruid'),
	 (20,4015075,'marcuscarr',NULL,NULL,'https://github.com/marcuscarr','https://avatars.githubusercontent.com/u/4015075?v=4',NULL,NULL,NULL,NULL,NULL,NULL,'',NULL,NULL,'MDQ6VXNlcjQwMTUwNzU=',NULL,NULL,false,NULL,'User',NULL,'https://api.github.com/users/marcuscarr');
INSERT INTO public.users (id,user_id,login,name,email,html_url,avatar_url,bio,company,created_at,blog,followers,following,gravatar_id,hireable,location,node_id,public_gists,public_repos,site_admin,twitter_username,type,updated_at,url) VALUES
	 (21,70884964,'Animatea',NULL,NULL,'https://github.com/Animatea','https://avatars.githubusercontent.com/u/70884964?v=4',NULL,NULL,NULL,NULL,NULL,NULL,'',NULL,NULL,'MDQ6VXNlcjcwODg0OTY0',NULL,NULL,false,NULL,'User',NULL,'https://api.github.com/users/Animatea'),
	 (22,7031616,'steilerDev',NULL,NULL,'https://github.com/steilerDev','https://avatars.githubusercontent.com/u/7031616?v=4',NULL,NULL,NULL,NULL,NULL,NULL,'',NULL,NULL,'MDQ6VXNlcjcwMzE2MTY=',NULL,NULL,false,NULL,'User',NULL,'https://api.github.com/users/steilerDev'),
	 (23,87733932,'ximelh',NULL,NULL,'https://github.com/ximelh','https://avatars.githubusercontent.com/u/87733932?v=4',NULL,NULL,NULL,NULL,NULL,NULL,'',NULL,NULL,'MDQ6VXNlcjg3NzMzOTMy',NULL,NULL,false,NULL,'User',NULL,'https://api.github.com/users/ximelh'),
	 (24,82463519,'Vladimir-Shane',NULL,NULL,'https://github.com/Vladimir-Shane','https://avatars.githubusercontent.com/u/82463519?v=4',NULL,NULL,NULL,NULL,NULL,NULL,'',NULL,NULL,'MDQ6VXNlcjgyNDYzNTE5',NULL,NULL,false,NULL,'User',NULL,'https://api.github.com/users/Vladimir-Shane'),
	 (25,47355593,'saadathussain1985',NULL,NULL,'https://github.com/saadathussain1985','https://avatars.githubusercontent.com/u/47355593?v=4',NULL,NULL,NULL,NULL,NULL,NULL,'',NULL,NULL,'MDQ6VXNlcjQ3MzU1NTkz',NULL,NULL,false,NULL,'User',NULL,'https://api.github.com/users/saadathussain1985'),
	 (26,21373700,'noahjkrueger',NULL,NULL,'https://github.com/noahjkrueger','https://avatars.githubusercontent.com/u/21373700?v=4',NULL,NULL,NULL,NULL,NULL,NULL,'',NULL,NULL,'MDQ6VXNlcjIxMzczNzAw',NULL,NULL,false,NULL,'User',NULL,'https://api.github.com/users/noahjkrueger'),
	 (27,42709757,'vincent-tvincent',NULL,NULL,'https://github.com/vincent-tvincent','https://avatars.githubusercontent.com/u/42709757?v=4',NULL,NULL,NULL,NULL,NULL,NULL,'',NULL,NULL,'MDQ6VXNlcjQyNzA5NzU3',NULL,NULL,false,NULL,'User',NULL,'https://api.github.com/users/vincent-tvincent'),
	 (28,25182860,'abulshah',NULL,NULL,'https://github.com/abulshah','https://avatars.githubusercontent.com/u/25182860?v=4',NULL,NULL,NULL,NULL,NULL,NULL,'',NULL,NULL,'MDQ6VXNlcjI1MTgyODYw',NULL,NULL,false,NULL,'User',NULL,'https://api.github.com/users/abulshah'),
	 (29,50131042,'KushRawat',NULL,NULL,'https://github.com/KushRawat','https://avatars.githubusercontent.com/u/50131042?v=4',NULL,NULL,NULL,NULL,NULL,NULL,'',NULL,NULL,'MDQ6VXNlcjUwMTMxMDQy',NULL,NULL,false,NULL,'User',NULL,'https://api.github.com/users/KushRawat'),
	 (30,86496933,'irem-koc',NULL,NULL,'https://github.com/irem-koc','https://avatars.githubusercontent.com/u/86496933?v=4',NULL,NULL,NULL,NULL,NULL,NULL,'',NULL,NULL,'MDQ6VXNlcjg2NDk2OTMz',NULL,NULL,false,NULL,'User',NULL,'https://api.github.com/users/irem-koc');
INSERT INTO public.users (id,user_id,login,name,email,html_url,avatar_url,bio,company,created_at,blog,followers,following,gravatar_id,hireable,location,node_id,public_gists,public_repos,site_admin,twitter_username,type,updated_at,url) VALUES
	 (31,36963647,'ZhuoerLyu',NULL,NULL,'https://github.com/ZhuoerLyu','https://avatars.githubusercontent.com/u/36963647?v=4',NULL,NULL,NULL,NULL,NULL,NULL,'',NULL,NULL,'MDQ6VXNlcjM2OTYzNjQ3',NULL,NULL,false,NULL,'User',NULL,'https://api.github.com/users/ZhuoerLyu'),
	 (32,12284331,'CMcConnor',NULL,NULL,'https://github.com/CMcConnor','https://avatars.githubusercontent.com/u/12284331?v=4',NULL,NULL,NULL,NULL,NULL,NULL,'',NULL,NULL,'MDQ6VXNlcjEyMjg0MzMx',NULL,NULL,false,NULL,'User',NULL,'https://api.github.com/users/CMcConnor'),
	 (33,100047273,'Robinson97798',NULL,NULL,'https://github.com/Robinson97798','https://avatars.githubusercontent.com/u/100047273?v=4',NULL,NULL,NULL,NULL,NULL,NULL,'',NULL,NULL,'U_kgDOBfaZqQ',NULL,NULL,false,NULL,'User',NULL,'https://api.github.com/users/Robinson97798'),
	 (34,95974654,'Jack-dp',NULL,NULL,'https://github.com/Jack-dp','https://avatars.githubusercontent.com/u/95974654?v=4',NULL,NULL,NULL,NULL,NULL,NULL,'',NULL,NULL,'U_kgDOBbh0_g',NULL,NULL,false,NULL,'User',NULL,'https://api.github.com/users/Jack-dp'),
	 (35,68614756,'HarryChui',NULL,NULL,'https://github.com/HarryChui','https://avatars.githubusercontent.com/u/68614756?v=4',NULL,NULL,NULL,NULL,NULL,NULL,'',NULL,NULL,'MDQ6VXNlcjY4NjE0NzU2',NULL,NULL,false,NULL,'User',NULL,'https://api.github.com/users/HarryChui'),
	 (36,92489983,'Flyforce1',NULL,NULL,'https://github.com/Flyforce1','https://avatars.githubusercontent.com/u/92489983?v=4',NULL,NULL,NULL,NULL,NULL,NULL,'',NULL,NULL,'U_kgDOBYNI_w',NULL,NULL,false,NULL,'User',NULL,'https://api.github.com/users/Flyforce1'),
	 (37,60532931,'kauanmatos224',NULL,NULL,'https://github.com/kauanmatos224','https://avatars.githubusercontent.com/u/60532931?v=4',NULL,NULL,NULL,NULL,NULL,NULL,'',NULL,NULL,'MDQ6VXNlcjYwNTMyOTMx',NULL,NULL,false,NULL,'User',NULL,'https://api.github.com/users/kauanmatos224'),
	 (38,100047477,'classhh1213',NULL,NULL,'https://github.com/classhh1213','https://avatars.githubusercontent.com/u/100047477?v=4',NULL,NULL,NULL,NULL,NULL,NULL,'',NULL,NULL,'U_kgDOBfaadQ',NULL,NULL,false,NULL,'User',NULL,'https://api.github.com/users/classhh1213'),
	 (39,84527857,'smarterToby',NULL,NULL,'https://github.com/smarterToby','https://avatars.githubusercontent.com/u/84527857?v=4',NULL,NULL,NULL,NULL,NULL,NULL,'',NULL,NULL,'MDQ6VXNlcjg0NTI3ODU3',NULL,NULL,false,NULL,'User',NULL,'https://api.github.com/users/smarterToby'),
	 (40,10836018,'yahyanouali',NULL,NULL,'https://github.com/yahyanouali','https://avatars.githubusercontent.com/u/10836018?v=4',NULL,NULL,NULL,NULL,NULL,NULL,'',NULL,NULL,'MDQ6VXNlcjEwODM2MDE4',NULL,NULL,false,NULL,'User',NULL,'https://api.github.com/users/yahyanouali');
INSERT INTO public.users (id,user_id,login,name,email,html_url,avatar_url,bio,company,created_at,blog,followers,following,gravatar_id,hireable,location,node_id,public_gists,public_repos,site_admin,twitter_username,type,updated_at,url) VALUES
	 (41,83154639,'kshitij-shakya',NULL,NULL,'https://github.com/kshitij-shakya','https://avatars.githubusercontent.com/u/83154639?v=4',NULL,NULL,NULL,NULL,NULL,NULL,'',NULL,NULL,'MDQ6VXNlcjgzMTU0NjM5',NULL,NULL,false,NULL,'User',NULL,'https://api.github.com/users/kshitij-shakya'),
	 (42,13206784,'jose-a-sa',NULL,NULL,'https://github.com/jose-a-sa','https://avatars.githubusercontent.com/u/13206784?v=4',NULL,NULL,NULL,NULL,NULL,NULL,'',NULL,NULL,'MDQ6VXNlcjEzMjA2Nzg0',NULL,NULL,false,NULL,'User',NULL,'https://api.github.com/users/jose-a-sa'),
	 (43,100047509,'hiwsadigy',NULL,NULL,'https://github.com/hiwsadigy','https://avatars.githubusercontent.com/u/100047509?v=4',NULL,NULL,NULL,NULL,NULL,NULL,'',NULL,NULL,'U_kgDOBfaalQ',NULL,NULL,false,NULL,'User',NULL,'https://api.github.com/users/hiwsadigy'),
	 (44,51394642,'whereislima',NULL,NULL,'https://github.com/whereislima','https://avatars.githubusercontent.com/u/51394642?v=4',NULL,NULL,NULL,NULL,NULL,NULL,'',NULL,NULL,'MDQ6VXNlcjUxMzk0NjQy',NULL,NULL,false,NULL,'User',NULL,'https://api.github.com/users/whereislima'),
	 (45,65954226,'moustafashahin122',NULL,NULL,'https://github.com/moustafashahin122','https://avatars.githubusercontent.com/u/65954226?v=4',NULL,NULL,NULL,NULL,NULL,NULL,'',NULL,NULL,'MDQ6VXNlcjY1OTU0MjI2',NULL,NULL,false,NULL,'User',NULL,'https://api.github.com/users/moustafashahin122'),
	 (46,43315242,'valekutce',NULL,NULL,'https://github.com/valekutce','https://avatars.githubusercontent.com/u/43315242?v=4',NULL,NULL,NULL,NULL,NULL,NULL,'',NULL,NULL,'MDQ6VXNlcjQzMzE1MjQy',NULL,NULL,false,NULL,'User',NULL,'https://api.github.com/users/valekutce'),
	 (47,92479423,'almayusuf',NULL,NULL,'https://github.com/almayusuf','https://avatars.githubusercontent.com/u/92479423?v=4',NULL,NULL,NULL,NULL,NULL,NULL,'',NULL,NULL,'U_kgDOBYMfvw',NULL,NULL,false,NULL,'User',NULL,'https://api.github.com/users/almayusuf'),
	 (48,59563423,'catafalc',NULL,NULL,'https://github.com/catafalc','https://avatars.githubusercontent.com/u/59563423?v=4',NULL,NULL,NULL,NULL,NULL,NULL,'',NULL,NULL,'MDQ6VXNlcjU5NTYzNDIz',NULL,NULL,false,NULL,'User',NULL,'https://api.github.com/users/catafalc'),
	 (49,96445998,'potatoland4492',NULL,NULL,'https://github.com/potatoland4492','https://avatars.githubusercontent.com/u/96445998?v=4',NULL,NULL,NULL,NULL,NULL,NULL,'',NULL,NULL,'U_kgDOBb-mLg',NULL,NULL,false,NULL,'User',NULL,'https://api.github.com/users/potatoland4492'),
	 (50,5208338,'PhylumChordata',NULL,NULL,'https://github.com/PhylumChordata','https://avatars.githubusercontent.com/u/5208338?v=4',NULL,NULL,NULL,NULL,NULL,NULL,'',NULL,NULL,'MDQ6VXNlcjUyMDgzMzg=',NULL,NULL,false,NULL,'User',NULL,'https://api.github.com/users/PhylumChordata');
INSERT INTO public.users (id,user_id,login,name,email,html_url,avatar_url,bio,company,created_at,blog,followers,following,gravatar_id,hireable,location,node_id,public_gists,public_repos,site_admin,twitter_username,type,updated_at,url) VALUES
	 (51,52103027,'shirinebadi',NULL,NULL,'https://github.com/shirinebadi','https://avatars.githubusercontent.com/u/52103027?v=4',NULL,NULL,NULL,NULL,NULL,NULL,'',NULL,NULL,'MDQ6VXNlcjUyMTAzMDI3',NULL,NULL,false,NULL,'User',NULL,'https://api.github.com/users/shirinebadi'),
	 (52,93732992,'restlessbraap',NULL,NULL,'https://github.com/restlessbraap','https://avatars.githubusercontent.com/u/93732992?v=4',NULL,NULL,NULL,NULL,NULL,NULL,'',NULL,NULL,'U_kgDOBZZAgA',NULL,NULL,false,NULL,'User',NULL,'https://api.github.com/users/restlessbraap'),
	 (53,48217288,'ArthurLuizS',NULL,NULL,'https://github.com/ArthurLuizS','https://avatars.githubusercontent.com/u/48217288?v=4',NULL,NULL,NULL,NULL,NULL,NULL,'',NULL,NULL,'MDQ6VXNlcjQ4MjE3Mjg4',NULL,NULL,false,NULL,'User',NULL,'https://api.github.com/users/ArthurLuizS'),
	 (54,79950985,'preetecool',NULL,NULL,'https://github.com/preetecool','https://avatars.githubusercontent.com/u/79950985?v=4',NULL,NULL,NULL,NULL,NULL,NULL,'',NULL,NULL,'MDQ6VXNlcjc5OTUwOTg1',NULL,NULL,false,NULL,'User',NULL,'https://api.github.com/users/preetecool'),
	 (55,47837876,'CristianCeccon',NULL,NULL,'https://github.com/CristianCeccon','https://avatars.githubusercontent.com/u/47837876?v=4',NULL,NULL,NULL,NULL,NULL,NULL,'',NULL,NULL,'MDQ6VXNlcjQ3ODM3ODc2',NULL,NULL,false,NULL,'User',NULL,'https://api.github.com/users/CristianCeccon'),
	 (56,99609533,'fossetoctave',NULL,NULL,'https://github.com/fossetoctave','https://avatars.githubusercontent.com/u/99609533?v=4',NULL,NULL,NULL,NULL,NULL,NULL,'',NULL,NULL,'U_kgDOBe_rvQ',NULL,NULL,false,NULL,'User',NULL,'https://api.github.com/users/fossetoctave'),
	 (57,25551525,'junkajii',NULL,NULL,'https://github.com/junkajii','https://avatars.githubusercontent.com/u/25551525?v=4',NULL,NULL,NULL,NULL,NULL,NULL,'',NULL,NULL,'MDQ6VXNlcjI1NTUxNTI1',NULL,NULL,false,NULL,'User',NULL,'https://api.github.com/users/junkajii'),
	 (58,2864845,'EdSG',NULL,NULL,'https://github.com/EdSG','https://avatars.githubusercontent.com/u/2864845?v=4',NULL,NULL,NULL,NULL,NULL,NULL,'',NULL,NULL,'MDQ6VXNlcjI4NjQ4NDU=',NULL,NULL,false,NULL,'User',NULL,'https://api.github.com/users/EdSG'),
	 (59,33314100,'malachiwa',NULL,NULL,'https://github.com/malachiwa','https://avatars.githubusercontent.com/u/33314100?v=4',NULL,NULL,NULL,NULL,NULL,NULL,'',NULL,NULL,'MDQ6VXNlcjMzMzE0MTAw',NULL,NULL,false,NULL,'User',NULL,'https://api.github.com/users/malachiwa'),
	 (60,32772298,'opeajibuwa',NULL,NULL,'https://github.com/opeajibuwa','https://avatars.githubusercontent.com/u/32772298?v=4',NULL,NULL,NULL,NULL,NULL,NULL,'',NULL,NULL,'MDQ6VXNlcjMyNzcyMjk4',NULL,NULL,false,NULL,'User',NULL,'https://api.github.com/users/opeajibuwa');
INSERT INTO public.users (id,user_id,login,name,email,html_url,avatar_url,bio,company,created_at,blog,followers,following,gravatar_id,hireable,location,node_id,public_gists,public_repos,site_admin,twitter_username,type,updated_at,url) VALUES
	 (61,76495844,'Paola0508',NULL,NULL,'https://github.com/Paola0508','https://avatars.githubusercontent.com/u/76495844?v=4',NULL,NULL,NULL,NULL,NULL,NULL,'',NULL,NULL,'MDQ6VXNlcjc2NDk1ODQ0',NULL,NULL,false,NULL,'User',NULL,'https://api.github.com/users/Paola0508'),
	 (62,14844582,'gstoica27',NULL,NULL,'https://github.com/gstoica27','https://avatars.githubusercontent.com/u/14844582?v=4',NULL,NULL,NULL,NULL,NULL,NULL,'',NULL,NULL,'MDQ6VXNlcjE0ODQ0NTgy',NULL,NULL,false,NULL,'User',NULL,'https://api.github.com/users/gstoica27'),
	 (63,94016766,'Dbudhram',NULL,NULL,'https://github.com/Dbudhram','https://avatars.githubusercontent.com/u/94016766?v=4',NULL,NULL,NULL,NULL,NULL,NULL,'',NULL,NULL,'U_kgDOBZqU_g',NULL,NULL,false,NULL,'User',NULL,'https://api.github.com/users/Dbudhram'),
	 (64,95304946,'HermanMazur',NULL,NULL,'https://github.com/HermanMazur','https://avatars.githubusercontent.com/u/95304946?v=4',NULL,NULL,NULL,NULL,NULL,NULL,'',NULL,NULL,'U_kgDOBa488g',NULL,NULL,false,NULL,'User',NULL,'https://api.github.com/users/HermanMazur'),
	 (65,98552093,'stale6read',NULL,NULL,'https://github.com/stale6read','https://avatars.githubusercontent.com/u/98552093?v=4',NULL,NULL,NULL,NULL,NULL,NULL,'',NULL,NULL,'U_kgDOBd_JHQ',NULL,NULL,false,NULL,'User',NULL,'https://api.github.com/users/stale6read'),
	 (66,16804778,'ladybugldb',NULL,NULL,'https://github.com/ladybugldb','https://avatars.githubusercontent.com/u/16804778?v=4',NULL,NULL,NULL,NULL,NULL,NULL,'',NULL,NULL,'MDQ6VXNlcjE2ODA0Nzc4',NULL,NULL,false,NULL,'User',NULL,'https://api.github.com/users/ladybugldb'),
	 (67,70917883,'JonnyOrtiz-source',NULL,NULL,'https://github.com/JonnyOrtiz-source','https://avatars.githubusercontent.com/u/70917883?v=4',NULL,NULL,NULL,NULL,NULL,NULL,'',NULL,NULL,'MDQ6VXNlcjcwOTE3ODgz',NULL,NULL,false,NULL,'User',NULL,'https://api.github.com/users/JonnyOrtiz-source'),
	 (68,33519337,'indernett',NULL,NULL,'https://github.com/indernett','https://avatars.githubusercontent.com/u/33519337?v=4',NULL,NULL,NULL,NULL,NULL,NULL,'',NULL,NULL,'MDQ6VXNlcjMzNTE5MzM3',NULL,NULL,false,NULL,'User',NULL,'https://api.github.com/users/indernett'),
	 (69,22763754,'bubblenote',NULL,NULL,'https://github.com/bubblenote','https://avatars.githubusercontent.com/u/22763754?v=4',NULL,NULL,NULL,NULL,NULL,NULL,'',NULL,NULL,'MDQ6VXNlcjIyNzYzNzU0',NULL,NULL,false,NULL,'User',NULL,'https://api.github.com/users/bubblenote'),
	 (70,64529130,'Verachill',NULL,NULL,'https://github.com/Verachill','https://avatars.githubusercontent.com/u/64529130?v=4',NULL,NULL,NULL,NULL,NULL,NULL,'',NULL,NULL,'MDQ6VXNlcjY0NTI5MTMw',NULL,NULL,false,NULL,'User',NULL,'https://api.github.com/users/Verachill');
INSERT INTO public.users (id,user_id,login,name,email,html_url,avatar_url,bio,company,created_at,blog,followers,following,gravatar_id,hireable,location,node_id,public_gists,public_repos,site_admin,twitter_username,type,updated_at,url) VALUES
	 (71,71658676,'Mofendes',NULL,NULL,'https://github.com/Mofendes','https://avatars.githubusercontent.com/u/71658676?v=4',NULL,NULL,NULL,NULL,NULL,NULL,'',NULL,NULL,'MDQ6VXNlcjcxNjU4Njc2',NULL,NULL,false,NULL,'User',NULL,'https://api.github.com/users/Mofendes'),
	 (72,59922721,'durontoalim',NULL,NULL,'https://github.com/durontoalim','https://avatars.githubusercontent.com/u/59922721?v=4',NULL,NULL,NULL,NULL,NULL,NULL,'',NULL,NULL,'MDQ6VXNlcjU5OTIyNzIx',NULL,NULL,false,NULL,'User',NULL,'https://api.github.com/users/durontoalim'),
	 (73,68287231,'patrickbindelli',NULL,NULL,'https://github.com/patrickbindelli','https://avatars.githubusercontent.com/u/68287231?v=4',NULL,NULL,NULL,NULL,NULL,NULL,'',NULL,NULL,'MDQ6VXNlcjY4Mjg3MjMx',NULL,NULL,false,NULL,'User',NULL,'https://api.github.com/users/patrickbindelli'),
	 (74,24397550,'VolkanGurbuz',NULL,NULL,'https://github.com/VolkanGurbuz','https://avatars.githubusercontent.com/u/24397550?v=4',NULL,NULL,NULL,NULL,NULL,NULL,'',NULL,NULL,'MDQ6VXNlcjI0Mzk3NTUw',NULL,NULL,false,NULL,'User',NULL,'https://api.github.com/users/VolkanGurbuz'),
	 (75,70252484,'mason-carreon',NULL,NULL,'https://github.com/mason-carreon','https://avatars.githubusercontent.com/u/70252484?v=4',NULL,NULL,NULL,NULL,NULL,NULL,'',NULL,NULL,'MDQ6VXNlcjcwMjUyNDg0',NULL,NULL,false,NULL,'User',NULL,'https://api.github.com/users/mason-carreon'),
	 (76,98269207,'marcolion',NULL,NULL,'https://github.com/marcolion','https://avatars.githubusercontent.com/u/98269207?v=4',NULL,NULL,NULL,NULL,NULL,NULL,'',NULL,NULL,'U_kgDOBdt4Fw',NULL,NULL,false,NULL,'User',NULL,'https://api.github.com/users/marcolion'),
	 (77,80713321,'yasser4sasuke',NULL,NULL,'https://github.com/yasser4sasuke','https://avatars.githubusercontent.com/u/80713321?v=4',NULL,NULL,NULL,NULL,NULL,NULL,'',NULL,NULL,'MDQ6VXNlcjgwNzEzMzIx',NULL,NULL,false,NULL,'User',NULL,'https://api.github.com/users/yasser4sasuke'),
	 (78,98466329,'ngborrelli',NULL,NULL,'https://github.com/ngborrelli','https://avatars.githubusercontent.com/u/98466329?v=4',NULL,NULL,NULL,NULL,NULL,NULL,'',NULL,NULL,'U_kgDOBd56GQ',NULL,NULL,false,NULL,'User',NULL,'https://api.github.com/users/ngborrelli'),
	 (79,100044131,'thekiwimango',NULL,NULL,'https://github.com/thekiwimango','https://avatars.githubusercontent.com/u/100044131?v=4',NULL,NULL,NULL,NULL,NULL,NULL,'',NULL,NULL,'U_kgDOBfaNYw',NULL,NULL,false,NULL,'User',NULL,'https://api.github.com/users/thekiwimango'),
	 (80,99935794,'princewill3',NULL,NULL,'https://github.com/princewill3','https://avatars.githubusercontent.com/u/99935794?v=4',NULL,NULL,NULL,NULL,NULL,NULL,'',NULL,NULL,'U_kgDOBfTmMg',NULL,NULL,false,NULL,'User',NULL,'https://api.github.com/users/princewill3');
INSERT INTO public.users (id,user_id,login,name,email,html_url,avatar_url,bio,company,created_at,blog,followers,following,gravatar_id,hireable,location,node_id,public_gists,public_repos,site_admin,twitter_username,type,updated_at,url) VALUES
	 (81,90212425,'Shokirjon2002',NULL,NULL,'https://github.com/Shokirjon2002','https://avatars.githubusercontent.com/u/90212425?v=4',NULL,NULL,NULL,NULL,NULL,NULL,'',NULL,NULL,'MDQ6VXNlcjkwMjEyNDI1',NULL,NULL,false,NULL,'User',NULL,'https://api.github.com/users/Shokirjon2002'),
	 (82,60299042,'FRC-2867',NULL,NULL,'https://github.com/FRC-2867','https://avatars.githubusercontent.com/u/60299042?v=4',NULL,NULL,NULL,NULL,NULL,NULL,'',NULL,NULL,'MDEyOk9yZ2FuaXphdGlvbjYwMjk5MDQy',NULL,NULL,false,NULL,'Organization',NULL,'https://api.github.com/users/FRC-2867'),
	 (83,90347734,'ZD12T4NT',NULL,NULL,'https://github.com/ZD12T4NT','https://avatars.githubusercontent.com/u/90347734?v=4',NULL,NULL,NULL,NULL,NULL,NULL,'',NULL,NULL,'MDQ6VXNlcjkwMzQ3NzM0',NULL,NULL,false,NULL,'User',NULL,'https://api.github.com/users/ZD12T4NT'),
	 (84,7048991,'kenschenke',NULL,NULL,'https://github.com/kenschenke','https://avatars.githubusercontent.com/u/7048991?v=4',NULL,NULL,NULL,NULL,NULL,NULL,'',NULL,NULL,'MDQ6VXNlcjcwNDg5OTE=',NULL,NULL,false,NULL,'User',NULL,'https://api.github.com/users/kenschenke'),
	 (85,29563905,'LuffyUchiha',NULL,NULL,'https://github.com/LuffyUchiha','https://avatars.githubusercontent.com/u/29563905?v=4',NULL,NULL,NULL,NULL,NULL,NULL,'',NULL,NULL,'MDQ6VXNlcjI5NTYzOTA1',NULL,NULL,false,NULL,'User',NULL,'https://api.github.com/users/LuffyUchiha'),
	 (86,28495813,'leobaldoneto',NULL,NULL,'https://github.com/leobaldoneto','https://avatars.githubusercontent.com/u/28495813?v=4',NULL,NULL,NULL,NULL,NULL,NULL,'',NULL,NULL,'MDQ6VXNlcjI4NDk1ODEz',NULL,NULL,false,NULL,'User',NULL,'https://api.github.com/users/leobaldoneto'),
	 (87,59151327,'shovelmght',NULL,NULL,'https://github.com/shovelmght','https://avatars.githubusercontent.com/u/59151327?v=4',NULL,NULL,NULL,NULL,NULL,NULL,'',NULL,NULL,'MDQ6VXNlcjU5MTUxMzI3',NULL,NULL,false,NULL,'User',NULL,'https://api.github.com/users/shovelmght'),
	 (88,53161139,'iuryzanonni',NULL,NULL,'https://github.com/iuryzanonni','https://avatars.githubusercontent.com/u/53161139?v=4',NULL,NULL,NULL,NULL,NULL,NULL,'',NULL,NULL,'MDQ6VXNlcjUzMTYxMTM5',NULL,NULL,false,NULL,'User',NULL,'https://api.github.com/users/iuryzanonni'),
	 (89,100019578,'hitasha1620',NULL,NULL,'https://github.com/hitasha1620','https://avatars.githubusercontent.com/u/100019578?v=4',NULL,NULL,NULL,NULL,NULL,NULL,'',NULL,NULL,'U_kgDOBfYteg',NULL,NULL,false,NULL,'User',NULL,'https://api.github.com/users/hitasha1620'),
	 (90,4352885,'w21froster',NULL,NULL,'https://github.com/w21froster','https://avatars.githubusercontent.com/u/4352885?v=4',NULL,NULL,NULL,NULL,NULL,NULL,'',NULL,NULL,'MDQ6VXNlcjQzNTI4ODU=',NULL,NULL,false,NULL,'User',NULL,'https://api.github.com/users/w21froster');
INSERT INTO public.users (id,user_id,login,name,email,html_url,avatar_url,bio,company,created_at,blog,followers,following,gravatar_id,hireable,location,node_id,public_gists,public_repos,site_admin,twitter_username,type,updated_at,url) VALUES
	 (91,40922069,'alimahmoudi97',NULL,NULL,'https://github.com/alimahmoudi97','https://avatars.githubusercontent.com/u/40922069?v=4',NULL,NULL,NULL,NULL,NULL,NULL,'',NULL,NULL,'MDQ6VXNlcjQwOTIyMDY5',NULL,NULL,false,NULL,'User',NULL,'https://api.github.com/users/alimahmoudi97'),
	 (92,64448173,'jchawk455',NULL,NULL,'https://github.com/jchawk455','https://avatars.githubusercontent.com/u/64448173?v=4',NULL,NULL,NULL,NULL,NULL,NULL,'',NULL,NULL,'MDQ6VXNlcjY0NDQ4MTcz',NULL,NULL,false,NULL,'User',NULL,'https://api.github.com/users/jchawk455'),
	 (93,99621506,'gentlerhiz',NULL,NULL,'https://github.com/gentlerhiz','https://avatars.githubusercontent.com/u/99621506?v=4',NULL,NULL,NULL,NULL,NULL,NULL,'',NULL,NULL,'U_kgDOBfAagg',NULL,NULL,false,NULL,'User',NULL,'https://api.github.com/users/gentlerhiz'),
	 (94,5111693,'philliml74',NULL,NULL,'https://github.com/philliml74','https://avatars.githubusercontent.com/u/5111693?v=4',NULL,NULL,NULL,NULL,NULL,NULL,'',NULL,NULL,'MDQ6VXNlcjUxMTE2OTM=',NULL,NULL,false,NULL,'User',NULL,'https://api.github.com/users/philliml74'),
	 (95,51028108,'r8now',NULL,NULL,'https://github.com/r8now','https://avatars.githubusercontent.com/u/51028108?v=4',NULL,NULL,NULL,NULL,NULL,NULL,'',NULL,NULL,'MDQ6VXNlcjUxMDI4MTA4',NULL,NULL,false,NULL,'User',NULL,'https://api.github.com/users/r8now'),
	 (96,97486569,'natalietriffo',NULL,NULL,'https://github.com/natalietriffo','https://avatars.githubusercontent.com/u/97486569?v=4',NULL,NULL,NULL,NULL,NULL,NULL,'',NULL,NULL,'U_kgDOBc-G6Q',NULL,NULL,false,NULL,'User',NULL,'https://api.github.com/users/natalietriffo'),
	 (97,49716583,'nour-d',NULL,NULL,'https://github.com/nour-d','https://avatars.githubusercontent.com/u/49716583?v=4',NULL,NULL,NULL,NULL,NULL,NULL,'',NULL,NULL,'MDQ6VXNlcjQ5NzE2NTgz',NULL,NULL,false,NULL,'User',NULL,'https://api.github.com/users/nour-d'),
	 (98,1779628,'matthewholliday',NULL,NULL,'https://github.com/matthewholliday','https://avatars.githubusercontent.com/u/1779628?v=4',NULL,NULL,NULL,NULL,NULL,NULL,'',NULL,NULL,'MDQ6VXNlcjE3Nzk2Mjg=',NULL,NULL,false,NULL,'User',NULL,'https://api.github.com/users/matthewholliday'),
	 (99,55987003,'mouad333',NULL,NULL,'https://github.com/mouad333','https://avatars.githubusercontent.com/u/55987003?v=4',NULL,NULL,NULL,NULL,NULL,NULL,'',NULL,NULL,'MDQ6VXNlcjU1OTg3MDAz',NULL,NULL,false,NULL,'User',NULL,'https://api.github.com/users/mouad333');

INSERT INTO public.repositories (id,name,html_url,url,description,fork,full_name,is_private,node_id,repository_id,user_id) VALUES
	 (1,'tcc-draft','https://github.com/andrealoisio/tcc-draft','https://api.github.com/repos/andrealoisio/tcc-draft','Work for my specialization course in distributed systems archtecture',false,'andrealoisio/tcc-draft',false,'R_kgDOG38FTw',461309263,16350390),
	 (2,'Python','https://github.com/kerim47/Python','https://api.github.com/repos/kerim47/Python','Python projelerim',false,'kerim47/Python',false,'R_kgDOG38FUA',461309264,82260676),
	 (3,'terraform-demo','https://github.com/tsahaca/terraform-demo','https://api.github.com/repos/tsahaca/terraform-demo',NULL,false,'tsahaca/terraform-demo',false,'R_kgDOG38FUQ',461309265,9325425),
	 (4,'MyPostcard','https://github.com/FullStackJustin/MyPostcard','https://api.github.com/repos/FullStackJustin/MyPostcard','My first postcard assignment for 4geeks pre-course',false,'FullStackJustin/MyPostcard',false,'R_kgDOG38FUg',461309266,98195982),
	 (5,'cursoGit','https://github.com/amaruyum/cursoGit','https://api.github.com/repos/amaruyum/cursoGit','Git desde cero',false,'amaruyum/cursoGit',false,'R_kgDOG38FUw',461309267,70615264),
	 (6,'upload-artifact','https://github.com/faves4less/upload-artifact','https://api.github.com/repos/faves4less/upload-artifact',NULL,true,'faves4less/upload-artifact',false,'R_kgDOG38FVQ',461309269,83042710),
	 (7,'3d-world-portfolio','https://github.com/rashidwassan/3d-world-portfolio','https://api.github.com/repos/rashidwassan/3d-world-portfolio',NULL,false,'rashidwassan/3d-world-portfolio',false,'R_kgDOG38FWA',461309272,60597290),
	 (8,'git-remote2','https://github.com/chiba1999525/git-remote2','https://api.github.com/repos/chiba1999525/git-remote2',NULL,false,'chiba1999525/git-remote2',false,'R_kgDOG38FXg',461309278,93694596),
	 (9,'logseq-doc','https://github.com/DrRobertMurphy/logseq-doc','https://api.github.com/repos/DrRobertMurphy/logseq-doc','Unofficial Logseq Documentation',true,'DrRobertMurphy/logseq-doc',false,'R_kgDOG38FYA',461309280,12820826),
	 (10,'Fab583','https://github.com/Fab583/Fab583','https://api.github.com/repos/Fab583/Fab583','Config files for my GitHub profile.',false,'Fab583/Fab583',false,'R_kgDOG38FYQ',461309281,100047446);
INSERT INTO public.repositories (id,name,html_url,url,description,fork,full_name,is_private,node_id,repository_id,user_id) VALUES
	 (11,'NYT-MOVIE-APP','https://github.com/awelawi/NYT-MOVIE-APP','https://api.github.com/repos/awelawi/NYT-MOVIE-APP',NULL,false,'awelawi/NYT-MOVIE-APP',false,'R_kgDOG38FYg',461309282,73558557),
	 (12,'Python-Prep','https://github.com/Fatimaines/Python-Prep','https://api.github.com/repos/Fatimaines/Python-Prep',NULL,true,'Fatimaines/Python-Prep',false,'R_kgDOG38FZg',461309286,89318337),
	 (13,'Leocl745','https://github.com/Leocl745/Leocl745','https://api.github.com/repos/Leocl745/Leocl745','Config files for my GitHub profile.',false,'Leocl745/Leocl745',false,'R_kgDOG38FaA',461309288,100036577),
	 (14,'CodingNinjas','https://github.com/riteshmishra253/CodingNinjas','https://api.github.com/repos/riteshmishra253/CodingNinjas',NULL,true,'riteshmishra253/CodingNinjas',false,'R_kgDOG38FaQ',461309289,73328740),
	 (15,'react_week2_project_movie','https://github.com/rafacruz78gt/react_week2_project_movie','https://api.github.com/repos/rafacruz78gt/react_week2_project_movie',NULL,false,'rafacruz78gt/react_week2_project_movie',false,'R_kgDOG38Fag',461309290,92962705),
	 (16,'recetario','https://github.com/ForeroPaola/recetario','https://api.github.com/repos/ForeroPaola/recetario',NULL,true,'ForeroPaola/recetario',false,'R_kgDOG38Faw',461309291,100047450),
	 (17,'recipe_site','https://github.com/Zoro125/recipe_site','https://api.github.com/repos/Zoro125/recipe_site',NULL,false,'Zoro125/recipe_site',false,'R_kgDOG38FbA',461309292,95763600),
	 (18,'Magento-2-alicloud-cluster-terraform','https://github.com/magenx/Magento-2-alicloud-cluster-terraform','https://api.github.com/repos/magenx/Magento-2-alicloud-cluster-terraform',NULL,false,'magenx/Magento-2-alicloud-cluster-terraform',false,'R_kgDOG38Fbw',461309295,1591200),
	 (19,'AndroidHomeWorks','https://github.com/dzendruid/AndroidHomeWorks','https://api.github.com/repos/dzendruid/AndroidHomeWorks',NULL,false,'dzendruid/AndroidHomeWorks',false,'R_kgDOG38Fcg',461309298,61332171),
	 (20,'appts','https://github.com/marcuscarr/appts','https://api.github.com/repos/marcuscarr/appts',NULL,false,'marcuscarr/appts',false,'R_kgDOG38FdQ',461309301,4015075);
INSERT INTO public.repositories (id,name,html_url,url,description,fork,full_name,is_private,node_id,repository_id,user_id) VALUES
	 (21,'multibar-discord','https://github.com/Animatea/multibar-discord','https://api.github.com/repos/Animatea/multibar-discord','Plugin for python-multibar (discord API integration).',false,'Animatea/multibar-discord',false,'R_kgDOG38Fdg',461309302,70884964),
	 (22,'restic-docker','https://github.com/steilerDev/restic-docker','https://api.github.com/repos/steilerDev/restic-docker','Run the restic backup utility in a docker container',false,'steilerDev/restic-docker',false,'R_kgDOG38Fdw',461309303,7031616),
	 (23,'HDT4','https://github.com/ximelh/HDT4','https://api.github.com/repos/ximelh/HDT4','Hoja de trabajo 4, calculadora',false,'ximelh/HDT4',false,'R_kgDOG38FeQ',461309305,87733932),
	 (24,'jstdg7','https://github.com/Vladimir-Shane/jstdg7','https://api.github.com/repos/Vladimir-Shane/jstdg7','Example code from the book JavaScript: The Definitive Guide, 7th Edition',true,'Vladimir-Shane/jstdg7',false,'R_kgDOG38FfA',461309308,82463519),
	 (25,'Stallions','https://github.com/saadathussain1985/Stallions','https://api.github.com/repos/saadathussain1985/Stallions',NULL,false,'saadathussain1985/Stallions',false,'R_kgDOG38FfQ',461309309,47355593),
	 (26,'326-dubblestuforeo','https://github.com/noahjkrueger/326-dubblestuforeo','https://api.github.com/repos/noahjkrueger/326-dubblestuforeo','UMASS AMHERST CS326 FINAL PROJECT',false,'noahjkrueger/326-dubblestuforeo',false,'R_kgDOG38Ffg',461309310,21373700),
	 (27,'CS2303FinalHomework','https://github.com/vincent-tvincent/CS2303FinalHomework','https://api.github.com/repos/vincent-tvincent/CS2303FinalHomework',NULL,false,'vincent-tvincent/CS2303FinalHomework',false,'R_kgDOG38FgA',461309312,42709757),
	 (28,'CloudenabledWebApp','https://github.com/abulshah/CloudenabledWebApp','https://api.github.com/repos/abulshah/CloudenabledWebApp','CloudenabledWebApp for maven web app',true,'abulshah/CloudenabledWebApp',false,'R_kgDOG38FgQ',461309313,25182860),
	 (29,'react-app-debug','https://github.com/KushRawat/react-app-debug','https://api.github.com/repos/KushRawat/react-app-debug',NULL,false,'KushRawat/react-app-debug',false,'R_kgDOG38Fgg',461309314,50131042),
	 (30,'data_types_algorithms_second','https://github.com/irem-koc/data_types_algorithms_second','https://api.github.com/repos/irem-koc/data_types_algorithms_second',NULL,false,'irem-koc/data_types_algorithms_second',false,'R_kgDOG38FhA',461309316,86496933);
INSERT INTO public.repositories (id,name,html_url,url,description,fork,full_name,is_private,node_id,repository_id,user_id) VALUES
	 (31,'FFmpeg','https://github.com/ZhuoerLyu/FFmpeg','https://api.github.com/repos/ZhuoerLyu/FFmpeg','Mirror of https://git.ffmpeg.org/ffmpeg.git',true,'ZhuoerLyu/FFmpeg',false,'R_kgDOG38Fiw',461309323,36963647),
	 (32,'SecureS3','https://github.com/CMcConnor/SecureS3','https://api.github.com/repos/CMcConnor/SecureS3','CloudFormation templates for secure deployment of S3 buckets in AWS',false,'CMcConnor/SecureS3',false,'R_kgDOG38FjQ',461309325,12284331),
	 (33,'freevps','https://github.com/Robinson97798/freevps','https://api.github.com/repos/Robinson97798/freevps',NULL,true,'Robinson97798/freevps',false,'R_kgDOG38FkQ',461309329,100047273),
	 (34,'Baikal--Travel-agency','https://github.com/Jack-dp/Baikal--Travel-agency','https://api.github.com/repos/Jack-dp/Baikal--Travel-agency',NULL,false,'Jack-dp/Baikal--Travel-agency',false,'R_kgDOG38FlQ',461309333,95974654),
	 (35,'cmr-linedetect','https://github.com/HarryChui/cmr-linedetect','https://api.github.com/repos/HarryChui/cmr-linedetect',NULL,false,'HarryChui/cmr-linedetect',false,'R_kgDOG38Flg',461309334,68614756),
	 (36,'jenkins-with-terraform','https://github.com/Flyforce1/jenkins-with-terraform','https://api.github.com/repos/Flyforce1/jenkins-with-terraform',NULL,true,'Flyforce1/jenkins-with-terraform',false,'R_kgDOG38Flw',461309335,92489983),
	 (37,'AppProject','https://github.com/kauanmatos224/AppProject','https://api.github.com/repos/kauanmatos224/AppProject','Projeto de Aplicação Mobile',true,'kauanmatos224/AppProject',false,'R_kgDOG38FmQ',461309337,60532931),
	 (38,'MagiskOnWSA','https://github.com/classhh1213/MagiskOnWSA','https://api.github.com/repos/classhh1213/MagiskOnWSA','Integrate Magisk root and Google Apps (OpenGApps) into WSA (Windows Subsystem for Android)',true,'classhh1213/MagiskOnWSA',false,'R_kgDOG38Fmg',461309338,100047477),
	 (39,'startup-of-the-year','https://github.com/smarterToby/startup-of-the-year','https://api.github.com/repos/smarterToby/startup-of-the-year','See it live ↓↓↓',false,'smarterToby/startup-of-the-year',false,'R_kgDOG38Fmw',461309339,84527857),
	 (40,'account-service','https://github.com/yahyanouali/account-service','https://api.github.com/repos/yahyanouali/account-service',NULL,false,'yahyanouali/account-service',false,'R_kgDOG38FpA',461309348,10836018);
INSERT INTO public.repositories (id,name,html_url,url,description,fork,full_name,is_private,node_id,repository_id,user_id) VALUES
	 (41,'Python-Projects','https://github.com/kshitij-shakya/Python-Projects','https://api.github.com/repos/kshitij-shakya/Python-Projects',NULL,false,'kshitij-shakya/Python-Projects',false,'R_kgDOG38Fpg',461309350,83154639),
	 (42,'homebrew-tap','https://github.com/jose-a-sa/homebrew-tap','https://api.github.com/repos/jose-a-sa/homebrew-tap','The Macaulay2 tap for Homebrew',true,'jose-a-sa/homebrew-tap',false,'R_kgDOG38Fpw',461309351,13206784),
	 (43,'hiwsadigy','https://github.com/hiwsadigy/hiwsadigy','https://api.github.com/repos/hiwsadigy/hiwsadigy','Config files for my GitHub profile.',false,'hiwsadigy/hiwsadigy',false,'R_kgDOG38FqQ',461309353,100047509),
	 (44,'forms','https://github.com/whereislima/forms','https://api.github.com/repos/whereislima/forms',NULL,false,'whereislima/forms',false,'R_kgDOG38Fqg',461309354,51394642),
	 (45,'grad_pro','https://github.com/moustafashahin122/grad_pro','https://api.github.com/repos/moustafashahin122/grad_pro',NULL,false,'moustafashahin122/grad_pro',false,'R_kgDOG38Fqw',461309355,65954226),
	 (46,'foto-text-elements','https://github.com/valekutce/foto-text-elements','https://api.github.com/repos/valekutce/foto-text-elements',NULL,false,'valekutce/foto-text-elements',false,'R_kgDOG38Frg',461309358,43315242),
	 (47,'jenkins-class','https://github.com/almayusuf/jenkins-class','https://api.github.com/repos/almayusuf/jenkins-class',NULL,true,'almayusuf/jenkins-class',false,'R_kgDOG38FsA',461309360,92479423),
	 (48,'siir1','https://github.com/catafalc/siir1','https://api.github.com/repos/catafalc/siir1',NULL,false,'catafalc/siir1',false,'R_kgDOG38FsQ',461309361,59563423),
	 (49,'rhythmtick','https://github.com/potatoland4492/rhythmtick','https://api.github.com/repos/potatoland4492/rhythmtick',NULL,false,'potatoland4492/rhythmtick',false,'R_kgDOG38Fsg',461309362,96445998),
	 (50,'learn-to-program-w-assembly','https://github.com/PhylumChordata/learn-to-program-w-assembly','https://api.github.com/repos/PhylumChordata/learn-to-program-w-assembly','Source Code for ''Learn to Program with Assembly'' by Jonathan Bartlett',true,'PhylumChordata/learn-to-program-w-assembly',false,'R_kgDOG38FtA',461309364,5208338);
INSERT INTO public.repositories (id,name,html_url,url,description,fork,full_name,is_private,node_id,repository_id,user_id) VALUES
	 (51,'smart-office','https://github.com/shirinebadi/smart-office','https://api.github.com/repos/shirinebadi/smart-office','Smart Office is a project to control the entrance of users and the light value of their room at office',false,'shirinebadi/smart-office',false,'R_kgDOG38FtQ',461309365,52103027),
	 (52,'odin-landing-page','https://github.com/restlessbraap/odin-landing-page','https://api.github.com/repos/restlessbraap/odin-landing-page','A web landing page created using css flexbox.',false,'restlessbraap/odin-landing-page',false,'R_kgDOG38FuA',461309368,93732992),
	 (53,'API---FINANCAS','https://github.com/ArthurLuizS/API---FINANCAS','https://api.github.com/repos/ArthurLuizS/API---FINANCAS','Desenvolvimento de uma API REST com objetivo de aprendizado',false,'ArthurLuizS/API---FINANCAS',false,'R_kgDOG38FuQ',461309369,48217288),
	 (54,'vue-learning-resources-app','https://github.com/preetecool/vue-learning-resources-app','https://api.github.com/repos/preetecool/vue-learning-resources-app',NULL,false,'preetecool/vue-learning-resources-app',false,'R_kgDOG38FvQ',461309373,79950985),
	 (55,'MT--MisterTasks','https://github.com/CristianCeccon/MT--MisterTasks','https://api.github.com/repos/CristianCeccon/MT--MisterTasks',NULL,false,'CristianCeccon/MT--MisterTasks',false,'R_kgDOG38Fvw',461309375,47837876),
	 (56,'ooo','https://github.com/fossetoctave/ooo','https://api.github.com/repos/fossetoctave/ooo',NULL,false,'fossetoctave/ooo',false,'R_kgDOG38FxA',461309380,99609533),
	 (57,'UBL','https://github.com/junkajii/UBL','https://api.github.com/repos/junkajii/UBL',NULL,false,'junkajii/UBL',false,'R_kgDOG38Fxw',461309383,25551525),
	 (58,'EdSG','https://github.com/EdSG/EdSG','https://api.github.com/repos/EdSG/EdSG',NULL,false,'EdSG/EdSG',false,'R_kgDOG38FzQ',461309389,2864845),
	 (59,'gasMap','https://github.com/malachiwa/gasMap','https://api.github.com/repos/malachiwa/gasMap',NULL,false,'malachiwa/gasMap',false,'R_kgDOG38Fzg',461309390,33314100),
	 (60,'Intrusion-Detection-System-Using-CNN-and-Transfer-Learning','https://github.com/opeajibuwa/Intrusion-Detection-System-Using-CNN-and-Transfer-Learning','https://api.github.com/repos/opeajibuwa/Intrusion-Detection-System-Using-CNN-and-Transfer-Learning','Code for intrusion detection system (IDS) development using CNN models and transfer learning',true,'opeajibuwa/Intrusion-Detection-System-Using-CNN-and-Transfer-Learning',false,'R_kgDOG38F0g',461309394,32772298);
INSERT INTO public.repositories (id,name,html_url,url,description,fork,full_name,is_private,node_id,repository_id,user_id) VALUES
	 (61,'TravisPruebas1','https://github.com/Paola0508/TravisPruebas1','https://api.github.com/repos/Paola0508/TravisPruebas1',NULL,false,'Paola0508/TravisPruebas1',false,'R_kgDOG38F1Q',461309397,76495844),
	 (62,'detr','https://github.com/gstoica27/detr','https://api.github.com/repos/gstoica27/detr','End-to-End Object Detection with Transformers',true,'gstoica27/detr',false,'R_kgDOG38F2Q',461309401,14844582),
	 (63,'Risky-Business','https://github.com/Dbudhram/Risky-Business','https://api.github.com/repos/Dbudhram/Risky-Business',NULL,false,'Dbudhram/Risky-Business',false,'R_kgDOG38F2g',461309402,94016766),
	 (64,'jsband-demo','https://github.com/HermanMazur/jsband-demo','https://api.github.com/repos/HermanMazur/jsband-demo','jsband-demo',true,'HermanMazur/jsband-demo',false,'R_kgDOG38F2w',461309403,95304946),
	 (65,'DragonFruitStudios_repo2-','https://github.com/stale6read/DragonFruitStudios_repo2-','https://api.github.com/repos/stale6read/DragonFruitStudios_repo2-',NULL,true,'stale6read/DragonFruitStudios_repo2-',false,'R_kgDOG38F3A',461309404,98552093),
	 (66,'IronswornCompanion','https://github.com/ladybugldb/IronswornCompanion','https://api.github.com/repos/ladybugldb/IronswornCompanion','Ironsworn Companion is a digital toolkit for playing the tabletop roleplaying game Ironsworn.',true,'ladybugldb/IronswornCompanion',false,'R_kgDOG38F4g',461309410,16804778),
	 (67,'phase-0-completing-assignments','https://github.com/JonnyOrtiz-source/phase-0-completing-assignments','https://api.github.com/repos/JonnyOrtiz-source/phase-0-completing-assignments',NULL,true,'JonnyOrtiz-source/phase-0-completing-assignments',false,'R_kgDOG38F5Q',461309413,70917883),
	 (68,'indernett','https://github.com/indernett/indernett','https://api.github.com/repos/indernett/indernett','Config files for my GitHub profile.',false,'indernett/indernett',false,'R_kgDOG38F5g',461309414,33519337),
	 (69,'buildspace-dao-starter','https://github.com/bubblenote/buildspace-dao-starter','https://api.github.com/repos/bubblenote/buildspace-dao-starter',NULL,true,'bubblenote/buildspace-dao-starter',false,'R_kgDOG38F6A',461309416,22763754),
	 (70,'alias','https://github.com/Verachill/alias','https://api.github.com/repos/Verachill/alias',NULL,false,'Verachill/alias',false,'R_kgDOG38F6g',461309418,64529130);
INSERT INTO public.repositories (id,name,html_url,url,description,fork,full_name,is_private,node_id,repository_id,user_id) VALUES
	 (71,'demoWPFCLG','https://github.com/Mofendes/demoWPFCLG','https://api.github.com/repos/Mofendes/demoWPFCLG','M10 UF1 demo',false,'Mofendes/demoWPFCLG',false,'R_kgDOG38F7g',461309422,71658676),
	 (72,'HW','https://github.com/durontoalim/HW','https://api.github.com/repos/durontoalim/HW',NULL,false,'durontoalim/HW',false,'R_kgDOG38F8g',461309426,59922721),
	 (73,'sistemas-de-informacao','https://github.com/patrickbindelli/sistemas-de-informacao','https://api.github.com/repos/patrickbindelli/sistemas-de-informacao',NULL,false,'patrickbindelli/sistemas-de-informacao',false,'R_kgDOG38F9g',461309430,68287231),
	 (74,'React-Course-ToDo','https://github.com/VolkanGurbuz/React-Course-ToDo','https://api.github.com/repos/VolkanGurbuz/React-Course-ToDo',NULL,false,'VolkanGurbuz/React-Course-ToDo',false,'R_kgDOG38F-g',461309434,24397550),
	 (75,'5.4-Assignment-Loops-and-DOM','https://github.com/mason-carreon/5.4-Assignment-Loops-and-DOM','https://api.github.com/repos/mason-carreon/5.4-Assignment-Loops-and-DOM',NULL,false,'mason-carreon/5.4-Assignment-Loops-and-DOM',false,'R_kgDOG38F_A',461309436,70252484),
	 (76,'Javascript','https://github.com/marcolion/Javascript','https://api.github.com/repos/marcolion/Javascript',NULL,false,'marcolion/Javascript',false,'R_kgDOG38F_Q',461309437,98269207),
	 (77,'express','https://github.com/yasser4sasuke/express','https://api.github.com/repos/yasser4sasuke/express',NULL,false,'yasser4sasuke/express',false,'R_kgDOG38GAw',461309443,80713321),
	 (78,'AgenciaAutosDeportivosSASS_SEO_Borrelli','https://github.com/ngborrelli/AgenciaAutosDeportivosSASS_SEO_Borrelli','https://api.github.com/repos/ngborrelli/AgenciaAutosDeportivosSASS_SEO_Borrelli',NULL,false,'ngborrelli/AgenciaAutosDeportivosSASS_SEO_Borrelli',false,'R_kgDOG38GBw',461309447,98466329),
	 (79,'rewards-today','https://github.com/thekiwimango/rewards-today','https://api.github.com/repos/thekiwimango/rewards-today','Staking rewards aggregator',false,'thekiwimango/rewards-today',false,'R_kgDOG38GCA',461309448,100044131),
	 (80,'cash','https://github.com/princewill3/cash','https://api.github.com/repos/princewill3/cash',NULL,false,'princewill3/cash',false,'R_kgDOG38GCQ',461309449,99935794);
INSERT INTO public.repositories (id,name,html_url,url,description,fork,full_name,is_private,node_id,repository_id,user_id) VALUES
	 (81,'Javascript-lesson','https://github.com/Shokirjon2002/Javascript-lesson','https://api.github.com/repos/Shokirjon2002/Javascript-lesson',NULL,false,'Shokirjon2002/Javascript-lesson',false,'R_kgDOG38GCg',461309450,90212425),
	 (82,'Color-Sensor-v3-Examples','https://github.com/FRC-2867/Color-Sensor-v3-Examples','https://api.github.com/repos/FRC-2867/Color-Sensor-v3-Examples','Sample code for the REV Color Sensor V3 in FRC compatible with the roboRIO. For support reach out to support@revrobotics.com',true,'FRC-2867/Color-Sensor-v3-Examples',false,'R_kgDOG38GDg',461309454,60299042),
	 (83,'Starbucks-Landing-Page-2022-FEB','https://github.com/ZD12T4NT/Starbucks-Landing-Page-2022-FEB','https://api.github.com/repos/ZD12T4NT/Starbucks-Landing-Page-2022-FEB','Starbucks landing page in the year 2022 around February time. Its mobile and desktop responsive.',false,'ZD12T4NT/Starbucks-Landing-Page-2022-FEB',false,'R_kgDOG38GEQ',461309457,90347734),
	 (84,'teambroncobots.com','https://github.com/kenschenke/teambroncobots.com','https://api.github.com/repos/kenschenke/teambroncobots.com',NULL,true,'kenschenke/teambroncobots.com',false,'R_kgDOG38GEw',461309459,7048991),
	 (85,'ZombieChaos','https://github.com/LuffyUchiha/ZombieChaos','https://api.github.com/repos/LuffyUchiha/ZombieChaos',NULL,false,'LuffyUchiha/ZombieChaos',false,'R_kgDOG38GFQ',461309461,29563905),
	 (86,'ignite-react-desafio01','https://github.com/leobaldoneto/ignite-react-desafio01','https://api.github.com/repos/leobaldoneto/ignite-react-desafio01',NULL,false,'leobaldoneto/ignite-react-desafio01',false,'R_kgDOG38GFw',461309463,28495813),
	 (87,'Distortion','https://github.com/shovelmght/Distortion','https://api.github.com/repos/shovelmght/Distortion','puzzel game',false,'shovelmght/Distortion',false,'R_kgDOG38GGg',461309466,59151327),
	 (88,'bootcamp-game-2D','https://github.com/iuryzanonni/bootcamp-game-2D','https://api.github.com/repos/iuryzanonni/bootcamp-game-2D','Projeto desenvolvido para conclusão do Bootcamp Take Blip Web Developer.',false,'iuryzanonni/bootcamp-game-2D',false,'R_kgDOG38GGw',461309467,53161139),
	 (89,'bullseye','https://github.com/hitasha1620/bullseye','https://api.github.com/repos/hitasha1620/bullseye',NULL,false,'hitasha1620/bullseye',false,'R_kgDOG38GHA',461309468,100019578),
	 (90,'vs_live_share_demo','https://github.com/w21froster/vs_live_share_demo','https://api.github.com/repos/w21froster/vs_live_share_demo',NULL,false,'w21froster/vs_live_share_demo',false,'R_kgDOG38GHw',461309471,4352885);
INSERT INTO public.repositories (id,name,html_url,url,description,fork,full_name,is_private,node_id,repository_id,user_id) VALUES
	 (91,'website','https://github.com/alimahmoudi97/website','https://api.github.com/repos/alimahmoudi97/website',NULL,false,'alimahmoudi97/website',false,'R_kgDOG38GIA',461309472,40922069),
	 (92,'Web_Fundamentals','https://github.com/jchawk455/Web_Fundamentals','https://api.github.com/repos/jchawk455/Web_Fundamentals',NULL,false,'jchawk455/Web_Fundamentals',false,'R_kgDOG38GIw',461309475,64448173),
	 (93,'test','https://github.com/gentlerhiz/test','https://api.github.com/repos/gentlerhiz/test','Seeing how things goes',false,'gentlerhiz/test',false,'R_kgDOG38GJA',461309476,99621506),
	 (94,'ungoogled-chromium-windows','https://github.com/philliml74/ungoogled-chromium-windows','https://api.github.com/repos/philliml74/ungoogled-chromium-windows','Windows packaging for ungoogled-chromium',true,'philliml74/ungoogled-chromium-windows',false,'R_kgDOG38GJQ',461309477,5111693),
	 (95,'Moment3-CD','https://github.com/r8now/Moment3-CD','https://api.github.com/repos/r8now/Moment3-CD',NULL,false,'r8now/Moment3-CD',false,'R_kgDOG38GJw',461309479,51028108),
	 (96,'password-homework','https://github.com/natalietriffo/password-homework','https://api.github.com/repos/natalietriffo/password-homework',NULL,false,'natalietriffo/password-homework',false,'R_kgDOG38GKg',461309482,97486569),
	 (97,'manual-testing-practice','https://github.com/nour-d/manual-testing-practice','https://api.github.com/repos/nour-d/manual-testing-practice',NULL,false,'nour-d/manual-testing-practice',false,'R_kgDOG38GMw',461309491,49716583),
	 (98,'Hugging-Face-Transformer-Examples','https://github.com/matthewholliday/Hugging-Face-Transformer-Examples','https://api.github.com/repos/matthewholliday/Hugging-Face-Transformer-Examples','Simple examples of using language transformers with the Hugging Face platform.',false,'matthewholliday/Hugging-Face-Transformer-Examples',false,'R_kgDOG38GNQ',461309493,1779628),
	 (99,'cloudshell-novnc-automation','https://github.com/Robinson97798/cloudshell-novnc-automation','https://api.github.com/repos/Robinson97798/cloudshell-novnc-automation','Google Cloudshell Free VPS with novnc and Ngrok - AUTOMATION',true,'Robinson97798/cloudshell-novnc-automation',false,'R_kgDOG38GNw',461309495,100047273),
	 (100,'Slider','https://github.com/mouad333/Slider','https://api.github.com/repos/mouad333/Slider',NULL,false,'mouad333/Slider',false,'R_kgDOG38GOw',461309499,55987003);
